# Generated by Django 6.0.4 on 2026-05-02 11:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['expense_type__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LiabilityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Liability Categories',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('effective_from', models.DateField()),
                ('change_reason', models.TextField(blank=True)),
                ('expense_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='finance.expenseitem')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='finance.expensetype'),
        ),
        migrations.CreateModel(
            name='LiabilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='finance.liabilitycategory')),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LiabilityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=6, help_text='Interest rate (e.g., 0.12 = 12%)', max_digits=10, null=True)),
                ('amount_per_return', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('liability_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='finance.liabilitytype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('EXPENSE', 'Expense'), ('LIABILITY', 'Liability'), ('PREPAYMENT', 'Prepayment')], max_length=50)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference_number', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('expense_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.expenseitem')),
                ('liability_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.liabilityitem')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.paymentmethod')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='LiabilityPaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('liability_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_details', to='finance.liabilityitem')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liability_details', to='finance.payment')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligation_type', models.CharField(choices=[('EXPENSE', 'Expense'), ('LIABILITY', 'Liability')], max_length=50)),
                ('obligation_date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prepayment_applied', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('expense_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligations', to='finance.expenseitem')),
                ('liability_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obligations', to='finance.liabilityitem')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='obligation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.paymentobligation'),
        ),
        migrations.CreateModel(
            name='Prepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_prepaid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_utilized', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('prepayment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Exhausted', 'Exhausted'), ('Cancelled', 'Cancelled')], default='Active', max_length=50)),
                ('expense_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepayments', to='finance.expenseitem')),
                ('liability_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepayments', to='finance.liabilityitem')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepayments', to='finance.payment')),
            ],
            options={
                'ordering': ['-prepayment_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allocation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.paymentobligation')),
                ('prepayment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.prepayment')),
            ],
            options={
                'ordering': ['-allocation_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurrencePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('DAILY', 'Daily'), ('ONE_TIME', 'One Time')], max_length=50)),
                ('frequency_value', models.PositiveIntegerField(default=1)),
                ('specific_day_of_week', models.IntegerField(blank=True, null=True)),
                ('specific_day_of_month', models.IntegerField(default=-1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expense_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to='finance.expenseitem')),
            ],
            options={
                'ordering': ['expense_item__name'],
            },
        ),
    ]
