# Generated by Django 6.0.4 on 2026-05-03 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(unique=True)),
                ('opened_by', models.CharField(max_length=255)),
                ('closed_by', models.CharField(blank=True, max_length=255)),
                ('opening_float', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variance_explanation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('VARIANCE', 'Variance')], default='OPEN', max_length=20)),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseTypeExtra',
            fields=[
                ('expense_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extra', serialize=False, to='finance.expensetype')),
                ('is_cogs', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='LiabilityItemExtra',
            fields=[
                ('liability_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extra', serialize=False, to='finance.liabilityitem')),
                ('interest_type', models.CharField(choices=[('FLAT', 'Flat Rate'), ('REDUCING', 'Reducing Balance'), ('NONE', 'No Interest')], default='REDUCING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('CASH', 'Physical Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK', 'Bank / Cheque')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentExtra',
            fields=[
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extra', serialize=False, to='finance.payment')),
                ('payment_reference', models.CharField(blank=True, db_index=True, max_length=50)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='finance.paymentcategory')),
            ],
            options={
                'ordering': ['category__display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodCategory',
            fields=[
                ('payment_method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='category_link', serialize=False, to='finance.paymentmethod')),
                ('clears_immediately', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.paymentcategory')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.paymentprovider')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(help_text='1=January … 12=December')),
                ('budget_type', models.CharField(choices=[('REVENUE', 'Net Sales Revenue'), ('COGS', 'Cost of Goods Sold'), ('EXPENSE', 'Operating Expense')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('expense_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='finance.expensetype')),
            ],
            options={
                'ordering': ['financial_year', 'month', 'budget_type'],
                'unique_together': {('financial_year', 'month', 'budget_type', 'expense_type')},
            },
        ),
        migrations.CreateModel(
            name='SessionBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('system_expected_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('uncleared_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.paymentmethod')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='finance.cashregistersession')),
            ],
            options={
                'unique_together': {('session', 'payment_method')},
            },
        ),
    ]
