# Generated by Django 6.0.4 on 2026-05-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_cashregistersession_expensetypeextra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObligationGeneratorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run_date', models.DateField(unique=True)),
            ],
            options={
                'ordering': ['-last_run_date'],
            },
        ),
    ]
