# Generated by Django 6.0.4 on 2026-05-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_budgetline_created_at_budgetline_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentobligation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='paymentobligation',
            unique_together={('expense_item', 'due_date', 'obligation_type')},
        ),
    ]
