# Generated by Django 6.0.4 on 2026-05-03 06:23

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='acquisition_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_reference',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Original purchase price (TZS).', max_digits=15),
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_method',
            field=models.CharField(choices=[('SL', 'Straight-Line'), ('DB', 'Declining Balance'), ('NONE', 'No Depreciation')], default='SL', max_length=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.20'), help_text='Annual rate e.g. 0.20 = 20% p.a.', max_digits=5),
        ),
        migrations.AddField(
            model_name='asset',
            name='disposal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='disposal_proceeds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='asset',
            name='residual_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='asset',
            name='worth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
