from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator
from django.db.models import Sum
from django.db.models.functions import Coalesce
from decimal import Decimal


class PaymentMethod(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class ExpenseType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class ExpenseItem(models.Model):
    """A specific recurring expense — e.g., 'Shop Rent', 'Electricity Bill'."""
    expense_type = models.ForeignKey(ExpenseType, on_delete=models.PROTECT, related_name='items')
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['expense_type__name', 'name']

    def __str__(self):
        return f"{self.expense_type.name} — {self.name}"

    def current_rate(self) -> Decimal:
        """Returns the rate effective as of today."""
        rate = self.rates.filter(
            effective_from__lte=timezone.now().date()
        ).order_by('-effective_from').first()
        return rate.amount if rate else Decimal('0')


class ExpenseRate(models.Model):
    """Historical rate log — rate changes are tracked, not overwritten."""
    expense_item = models.ForeignKey(ExpenseItem, on_delete=models.CASCADE, related_name='rates')
    amount = models.DecimalField(max_digits=15, decimal_places=2, validators=[MinValueValidator(Decimal('0'))])
    effective_from = models.DateField()
    change_reason = models.TextField(blank=True)

    class Meta:
        ordering = ['-effective_from']

    def __str__(self):
        return f"{self.expense_item.name} — {self.amount} from {self.effective_from}"


class RecurrencePattern(models.Model):
    """Defines how often an expense obligation is generated."""
    RECURRENCE_TYPES = [
        ('MONTHLY', 'Monthly'),
        ('WEEKLY', 'Weekly'),
        ('DAILY', 'Daily'),
        ('ONE_TIME', 'One Time'),
    ]
    expense_item = models.ForeignKey(ExpenseItem, on_delete=models.CASCADE, related_name='recurrences')
    recurrence_type = models.CharField(max_length=50, choices=RECURRENCE_TYPES)
    frequency_value = models.PositiveIntegerField(default=1)
    specific_day_of_week = models.IntegerField(null=True, blank=True)   # 1=Mon … 7=Sun; 0=last; negative=offset
    specific_day_of_month = models.IntegerField(default=-1)             # 1–31; 0=last; negative=offset from last
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ['expense_item__name']

    def __str__(self):
        return f"{self.expense_item.name} — {self.recurrence_type}"

    def calculate_due_date(self, base_date):
        """
        Mirrors VBA CalculateDueDate() from modPayables.
        Supports last-day and negative offset conventions.
        """
        import calendar

        if self.recurrence_type == 'MONTHLY':
            last_day = calendar.monthrange(base_date.year, base_date.month)[1]
            dom = self.specific_day_of_month
            if dom is None or dom == 0:
                return base_date.replace(day=last_day)
            elif dom < 0:
                from datetime import timedelta
                return base_date.replace(day=last_day) + timedelta(days=dom)
            else:
                return base_date.replace(day=min(dom, last_day))

        elif self.recurrence_type == 'WEEKLY':
            from datetime import timedelta
            dow = self.specific_day_of_week or 1
            days_to_end_of_week = (7 - base_date.weekday()) % 7 or 7
            week_end = base_date + timedelta(days=days_to_end_of_week)
            if dow < 0:
                return week_end + timedelta(days=dow)
            return week_end

        return base_date


class PaymentObligation(models.Model):
    """
    Auto-generated obligation entry for each due expense/liability period.
    Generated by management command `generate_obligations`.
    Mirrors modPayables obligation generation logic.
    """
    OBLIGATION_TYPES = [('EXPENSE', 'Expense'), ('LIABILITY', 'Liability')]
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('PARTIAL', 'Partially Paid'),
        ('PAID', 'Paid'),
        ('OVERDUE', 'Overdue'),
    ]

    expense_item = models.ForeignKey(ExpenseItem, on_delete=models.SET_NULL,
                                      null=True, blank=True, related_name='obligations')
    liability_item = models.ForeignKey('LiabilityItem', on_delete=models.SET_NULL,
                                        null=True, blank=True, related_name='obligations')
    obligation_type = models.CharField(max_length=50, choices=OBLIGATION_TYPES)
    obligation_date = models.DateField()
    due_date = models.DateField()
    amount_due = models.DecimalField(max_digits=15, decimal_places=2)
    prepayment_applied = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    amount_paid = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    description = models.TextField(blank=True)

    class Meta:
        ordering = ['due_date']

    def __str__(self):
        return f"Obligation #{self.pk} — {self.due_date} — {self.amount_due}"

    @property
    def balance(self):
        return self.amount_due - self.prepayment_applied - self.amount_paid

    @property
    def payment_status(self):
        if self.balance <= 0:
            return 'PAID'
        elif self.amount_paid > 0 or self.prepayment_applied > 0:
            return 'PARTIAL'
        elif self.due_date < timezone.now().date():
            return 'OVERDUE'
        return 'PENDING'


class Payment(models.Model):
    """Actual cash outflow against an obligation or directly against an expense/liability."""
    PAYMENT_TYPES = [('EXPENSE', 'Expense'), ('LIABILITY', 'Liability'), ('PREPAYMENT', 'Prepayment')]

    obligation = models.ForeignKey(PaymentObligation, on_delete=models.SET_NULL,
                                    null=True, blank=True, related_name='payments')
    expense_item = models.ForeignKey(ExpenseItem, on_delete=models.SET_NULL,
                                      null=True, blank=True, related_name='payments')
    liability_item = models.ForeignKey('LiabilityItem', on_delete=models.SET_NULL,
                                        null=True, blank=True, related_name='payments')
    payment_type = models.CharField(max_length=50, choices=PAYMENT_TYPES)
    payment_date = models.DateTimeField(default=timezone.now)
    amount_paid = models.DecimalField(max_digits=15, decimal_places=2)
    payment_method = models.ForeignKey(PaymentMethod, on_delete=models.PROTECT)
    reference_number = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)

    class Meta:
        ordering = ['-payment_date']

    def __str__(self):
        return f"Payment #{self.pk} — {self.amount_paid} on {self.payment_date.date()}"


class Prepayment(models.Model):
    """Advance payment that can be allocated across future obligations."""
    STATUS_CHOICES = [('Active', 'Active'), ('Exhausted', 'Exhausted'), ('Cancelled', 'Cancelled')]

    payment = models.ForeignKey(Payment, on_delete=models.PROTECT, related_name='prepayments')
    expense_item = models.ForeignKey(ExpenseItem, on_delete=models.SET_NULL,
                                      null=True, blank=True, related_name='prepayments')
    liability_item = models.ForeignKey('LiabilityItem', on_delete=models.SET_NULL,
                                        null=True, blank=True, related_name='prepayments')
    total_prepaid = models.DecimalField(max_digits=15, decimal_places=2)
    amount_utilized = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    prepayment_date = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='Active')

    class Meta:
        ordering = ['-prepayment_date']

    def __str__(self):
        return f"Prepayment #{self.pk} — {self.total_prepaid}"

    @property
    def amount_remaining(self):
        return self.total_prepaid - self.amount_utilized


class PaymentAllocation(models.Model):
    """Links a prepayment to a specific obligation it covers."""
    prepayment = models.ForeignKey(Prepayment, on_delete=models.PROTECT, related_name='allocations')
    obligation = models.ForeignKey(PaymentObligation, on_delete=models.PROTECT, related_name='allocations')
    amount_allocated = models.DecimalField(max_digits=15, decimal_places=2)
    allocation_date = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-allocation_date']

    def __str__(self):
        return f"Allocation #{self.pk} — {self.amount_allocated}"


class LiabilityCategory(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'Liability Categories'

    def __str__(self):
        return self.name


class LiabilityType(models.Model):
    category = models.ForeignKey(LiabilityCategory, on_delete=models.PROTECT, related_name='types')
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ['category__name', 'name']

    def __str__(self):
        return f"{self.category.name} — {self.name}"


class LiabilityItem(models.Model):
    """A specific external loan or long-term liability."""
    liability_type = models.ForeignKey(LiabilityType, on_delete=models.PROTECT, related_name='items')
    name = models.CharField(max_length=255)
    original_amount = models.DecimalField(max_digits=15, decimal_places=2)
    start_date = models.DateField()
    maturity_date = models.DateField(null=True, blank=True)
    is_active = models.BooleanField(default=True)
    rate = models.DecimalField(max_digits=10, decimal_places=6, null=True, blank=True,
                                help_text='Interest rate (e.g., 0.12 = 12%)')
    amount_per_return = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    @property
    def current_balance(self):
        paid = self.payment_details.aggregate(
            t=Coalesce(Sum('principal_amount'), Decimal('0'))
        )['t']
        return self.original_amount - paid


class LiabilityPaymentDetail(models.Model):
    """Principal + interest breakdown for each liability payment."""
    payment = models.ForeignKey(Payment, on_delete=models.CASCADE, related_name='liability_details')
    liability_item = models.ForeignKey(LiabilityItem, on_delete=models.PROTECT,
                                        related_name='payment_details')
    principal_amount = models.DecimalField(max_digits=15, decimal_places=2)
    interest_amount = models.DecimalField(max_digits=15, decimal_places=2)
    balance_after_payment = models.DecimalField(max_digits=15, decimal_places=2, null=True, blank=True)
    payment_date = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-payment_date']

    def __str__(self):
        return f"Liability Payment #{self.pk} — {self.liability_item.name}"

# Create your models here.
