# Generated by Django 6.0.4 on 2026-05-02 11:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone_1', models.CharField(blank=True, max_length=30)),
                ('phone_2', models.CharField(blank=True, max_length=30)),
                ('nida_id', models.CharField(blank=True, max_length=255, verbose_name='NIDA ID')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_payment_date', models.DateField(blank=True, null=True)),
                ('product_spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='catalog.productspec')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='credit.debtor')),
            ],
            options={
                'verbose_name': 'Credit Sale (Debt)',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='DebtReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='credit.debt')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.paymentmethod')),
            ],
            options={
                'verbose_name': 'Debt Repayment',
                'ordering': ['-return_date'],
            },
        ),
    ]
