# Generated by Django 6.0.4 on 2026-05-03 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Expected repayment channel.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.paymentmethod'),
        ),
        migrations.AddField(
            model_name='debt',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='debtor',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Max outstanding balance. 0 = no limit.', max_digits=15),
        ),
        migrations.AddField(
            model_name='debtor',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Block new credit sales for this debtor.'),
        ),
    ]
