# Generated by Django 6.0.4 on 2026-05-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='carriage_inwards',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Transport/freight cost to bring goods to shop.', max_digits=15),
        ),
        migrations.AddField(
            model_name='purchase',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
