# Generated by Django 6.0.4 on 2026-05-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(choices=[('D1', 'Monthly Income Statement'), ('D2', 'Monthly Balance Sheet'), ('D3', 'Monthly Cash Flow'), ('D4', 'Monthly Expense Analysis'), ('D5', 'Monthly Debtor Aging'), ('D6', 'Monthly Liability Schedule'), ('D7', 'Monthly Drawings Summary'), ('E1', 'Quarterly Management Accounts'), ('E2', 'Quarterly Stock Valuation'), ('F1', 'Annual Income Statement'), ('F2', 'Annual Balance Sheet'), ('F5', 'Annual Budget vs Actual')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('generated_by', models.CharField(default='System', max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_by', models.CharField(blank=True, max_length=255)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField()),
                ('checksum', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-period_end', 'report_code'],
                'unique_together': {('report_code', 'period_start', 'period_end')},
            },
        ),
    ]
