# Generated by Django 6.0.4 on 2026-05-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspec',
            name='budget_monthly_sales_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productspec',
            name='cached_stock_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cached Stock Value (TZS)'),
        ),
        migrations.AddField(
            model_name='productspec',
            name='cached_wac',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cached Weighted Avg Cost'),
        ),
    ]
