# Generated by Django 6.0.4 on 2026-05-03 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productspec_budget_monthly_sales_qty_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='TZS amount for cash drawings.', max_digits=15),
        ),
        migrations.AddField(
            model_name='drawing',
            name='drawing_type',
            field=models.CharField(choices=[('GOODS', 'Goods'), ('CASH', 'Cash')], default='GOODS', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='product_spec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drawings', to='catalog.productspec'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
